### ISSUE TITLE
Deletes item in hand

### ISSUE THREAD

**Issue by phase** [chibill/Slabs#1]
Just give the item to the player, not delete what's in their hand.

**Comment by wgaylord** [comment]
I will do that when I finish fixing more bugs and making improvements.

**Comment by wgaylord** [comment]
Going to work on that soon.

**Comment by phase** [comment]
> soon

**Comment by wgaylord** [comment]
Yes like maybe before next year.

**Comment by wgaylord** [comment]
Fixed!
